
name: 'getground_test'
version: '1.2.2'
config-version: 2

profile: 'getground-test'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  getground-test:
    +materialized: table
